# Generated by Django 3.1.4 on 2020-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'Бумагу', 'verbose_name_plural': 'Бумага'},
        ),
        migrations.AddField(
            model_name='paper',
            name='density',
            field=models.PositiveSmallIntegerField(default=130, verbose_name='Грамматура'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cost',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='Бумага', max_length=50, verbose_name='Название'),
        ),
    ]
